# Generated by Django 3.0.8 on 2020-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('continent', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('postalcode', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=40)),
                ('num', models.CharField(max_length=15)),
                ('coordinates', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=20)),
                ('numflight', models.CharField(max_length=10)),
                ('takeoff', models.DateTimeField()),
                ('landing', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('chain', models.CharField(max_length=30)),
                ('stars', models.CharField(max_length=2)),
                ('category', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('telephone', models.CharField(max_length=15)),
                ('is_partner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_swimingpool', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_spa', models.BooleanField(default=False)),
                ('has_kindergarden', models.BooleanField(default=False)),
                ('has_single_room', models.BooleanField(default=False)),
                ('has_double_room', models.BooleanField(default=False)),
                ('has_cooking_24h', models.BooleanField(default=False)),
                ('has_checkin_24h', models.BooleanField(default=False)),
                ('has_all_inclusive', models.BooleanField(default=False)),
                ('has_half_board', models.BooleanField(default=False)),
                ('has_full_board', models.BooleanField(default=False)),
                ('has_only_breakfast', models.BooleanField(default=False)),
                ('allow_pet', models.BooleanField(default=True)),
                ('rating', models.CharField(max_length=2)),
                ('rating_business', models.CharField(max_length=2)),
                ('rating_family', models.CharField(max_length=2)),
                ('rating_single', models.CharField(max_length=2)),
                ('rating_couples', models.CharField(max_length=2)),
                ('rating_pet', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_reference', models.CharField(max_length=40)),
                ('comercial_reference', models.CharField(max_length=40)),
                ('include_hotel', models.BooleanField(default=False)),
                ('include_flight', models.BooleanField(default=False)),
                ('include_event', models.BooleanField(default=False)),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('refund', models.IntegerField()),
                ('cancelled', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
