# Generated by Django 3.0.8 on 2020-08-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo1',
            field=models.ImageField(null=True, upload_to='photos/Events/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='event',
            name='photo2',
            field=models.ImageField(null=True, upload_to='photos/Events/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='event',
            name='photo3',
            field=models.ImageField(null=True, upload_to='photos/Events/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='event',
            name='photo4',
            field=models.ImageField(null=True, upload_to='photos/Events/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='event',
            name='photo_main',
            field=models.ImageField(null=True, upload_to='photos/Events/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo1',
            field=models.ImageField(null=True, upload_to='photos/Hotels/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo2',
            field=models.ImageField(null=True, upload_to='photos/Hotels/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo3',
            field=models.ImageField(null=True, upload_to='photos/Hotels/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo4',
            field=models.ImageField(null=True, upload_to='photos/Hotels/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo_main',
            field=models.ImageField(null=True, upload_to='photos/Hotels/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo1',
            field=models.ImageField(null=True, upload_to='photos/Trips/%Y/%m/%d/photo1'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo2',
            field=models.ImageField(null=True, upload_to='photos/Trips/%Y/%m/%d/photo2'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo3',
            field=models.ImageField(null=True, upload_to='photos/Trips/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo4',
            field=models.ImageField(null=True, upload_to='photos/Trips/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo_main',
            field=models.ImageField(null=True, upload_to='photos/Trips/%Y/%m/%d/photo_main'),
        ),
    ]
