# Generated by Django 3.0.8 on 2020-08-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20200807_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo4',
        ),
    ]
