# Generated by Django 3.0.8 on 2020-08-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20200808_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating_business',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating_couples',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating_family',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating_pet',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating_single',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
