# Generated by Django 3.0.8 on 2020-08-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20200808_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coordinates',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='allow_pet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
