# Generated by Django 3.0.8 on 2020-08-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20200808_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='eventid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trips.Event'),
        ),
        migrations.AddField(
            model_name='address',
            name='hotelid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trips.Hotel'),
        ),
    ]
