# Generated by Django 3.0.8 on 2020-08-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20200808_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='eventid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.Event'),
        ),
        migrations.AlterField(
            model_name='address',
            name='hotelid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.Hotel'),
        ),
    ]
