# Generated by Django 3.0.8 on 2020-08-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_auto_20200808_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='continent',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='coordinates',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='num',
            field=models.CharField(default='00000', max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='postalcode',
            field=models.CharField(default='00000', max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='street',
            field=models.CharField(default='00000', max_length=40),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='hotel',
            name='continent',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='hotel',
            name='coordinates',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='hotel',
            name='num',
            field=models.CharField(default='00000', max_length=15),
        ),
        migrations.AddField(
            model_name='hotel',
            name='postalcode',
            field=models.CharField(default='00000', max_length=15),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street',
            field=models.CharField(default='00000', max_length=40),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
