# Generated by Django 3.0.8 on 2020-08-08 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_auto_20200808_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='numflight',
            new_name='flightnum',
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='airport',
            name='continent',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='airport',
            name='coordinates',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='airport',
            name='num',
            field=models.CharField(default='00000', max_length=15),
        ),
        migrations.AddField(
            model_name='airport',
            name='postalcode',
            field=models.CharField(default='00000', max_length=15),
        ),
        migrations.AddField(
            model_name='airport',
            name='street',
            field=models.CharField(default='00000', max_length=40),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trips.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=18),
        ),
    ]
