# Generated by Django 3.0.8 on 2020-08-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_auto_20200808_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flightnum',
        ),
    ]
