# Generated by Django 3.0.8 on 2020-08-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_remove_flight_flightnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flightnum',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
    ]
