# Generated by Django 3.0.8 on 2020-08-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_auto_20200808_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trips.Airport'),
        ),
    ]
