# Generated by Django 3.0.8 on 2020-08-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_auto_20200808_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='parking_price',
            field=models.DecimalField(decimal_places=2, default='00000', max_digits=4),
        ),
    ]
