# Generated by Django 3.0.8 on 2020-08-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_hotel_parking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='parking_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=4),
        ),
    ]
