# Generated by Django 3.0.8 on 2020-08-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_auto_20200809_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ring',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trips.Ring'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='all_inclusive_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='breakfast_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='double_room_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='full_board_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='half_board_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='kindergarden_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='single_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='spa_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='suite_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
    ]
