# Generated by Django 3.0.8 on 2020-08-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_auto_20200809_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ring',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='trips.Ring'),
        ),
        migrations.AddField(
            model_name='flight',
            name='ring',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='trips.Ring'),
        ),
        migrations.AddField(
            model_name='trip',
            name='ring',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='trips.Ring'),
        ),
    ]
