# Generated by Django 3.0.8 on 2020-08-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_auto_20200809_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring',
            name='sold_trips',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='ring',
            name='trips_in_stock',
            field=models.IntegerField(default='0'),
        ),
    ]
