# Generated by Django 3.0.8 on 2020-08-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_auto_20200809_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='TripTemplate',
        ),
    ]
