# Generated by Django 3.0.8 on 2020-08-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_auto_20200809_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptemplate',
            name='main_description',
            field=models.CharField(default='00000', max_length=120),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='secondary_description',
            field=models.TextField(default='00000', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='triptemplate',
            name='basic_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='triptemplate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HotelTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin', models.DateTimeField(default=False)),
                ('checkout', models.DateTimeField(default=False)),
                ('number_of_single_rooms', models.IntegerField(default=False)),
                ('number_of_double_rooms', models.IntegerField(default=False)),
                ('number_of_suites', models.IntegerField(default=False)),
                ('parking_slots', models.IntegerField(default=False)),
                ('spa_tickets', models.IntegerField(default=False)),
                ('kindergarden_tickets', models.IntegerField(default=False)),
                ('breakfast_tickets', models.IntegerField(default=False)),
                ('fullboard_tickets', models.IntegerField(default=False)),
                ('halfboard_tickets', models.IntegerField(default=False)),
                ('all_inclusive_tickets', models.IntegerField(default=False)),
                ('people_to_airport_transfer', models.IntegerField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=False, max_digits=7)),
                ('hotelid', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='FlightTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_tickets', models.IntegerField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=False, max_digits=6)),
                ('go_flight', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.Flight')),
                ('return_flight', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trips.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='EventTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_tickets', models.IntegerField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=False, max_digits=6)),
                ('eventid', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.Event')),
            ],
        ),
    ]
