# Generated by Django 3.0.8 on 2020-08-09 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_useraccount_firstname'),
        ('trips', '0023_auto_20200809_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('w', 'Wish list'), ('B', 'Basket case'), ('X', 'Charged'), ('C', 'Cancelled'), ('R', 'Refunded'), ('I', 'Inactive')], default='I', max_length=1)),
                ('eventTripID', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.EventTrip')),
                ('flightTripID', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.FlightTrip')),
                ('hotelTripID', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.Hotel')),
                ('tripTemplateID', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.TripTemplate')),
                ('userID', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='pages.UserAccount')),
            ],
        ),
    ]
