# Generated by Django 3.0.8 on 2020-08-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0025_auto_20200809_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='hotelTripID',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.HotelTrip'),
        ),
    ]
