# Generated by Django 3.0.8 on 2020-08-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_auto_20200810_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighttrip',
            name='ring',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.Ring'),
        ),
    ]
