# Generated by Django 3.0.8 on 2020-08-10 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0027_flighttrip_ring'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighttrip',
            name='week_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(53), django.core.validators.MinValueValidator(0)]),
        ),
    ]
