# Generated by Django 3.0.8 on 2020-08-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0028_flighttrip_week_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flighttrip',
            old_name='total_tickets',
            new_name='people',
        ),
    ]
