# Generated by Django 3.0.8 on 2020-08-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0029_auto_20200810_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteltrip',
            name='ring',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='trips.Ring'),
        ),
    ]
