# Generated by Django 3.0.8 on 2020-08-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0030_hoteltrip_ring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteltrip',
            name='ring',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='trips.Ring'),
        ),
    ]
