# Generated by Django 3.0.8 on 2020-08-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0031_auto_20200810_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptemplate',
            name='marketing_message',
            field=models.CharField(default='Last days!!', max_length=60),
        ),
    ]
