# Generated by Django 3.0.8 on 2020-08-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0032_triptemplate_marketing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptemplate',
            name='img_1',
            field=models.ImageField(default='00000', null=True, upload_to='photos/Trips/%Y/%m/%d/photo_1'),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='img_2',
            field=models.ImageField(default='00000', null=True, upload_to='photos/Trips/%Y/%m/%d/photo_2'),
        ),
    ]
