# Generated by Django 3.0.8 on 2020-08-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0041_auto_20200826_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triptemplate',
            name='eventtrip_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.EventTrip'),
        ),
    ]
