# Generated by Django 3.0.8 on 2020-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0042_auto_20200827_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring',
            name='city',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='ring',
            name='continent',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ring',
            name='country',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='date_to_go',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='date_to_return',
            field=models.DateTimeField(null=True),
        ),
    ]
