# Generated by Django 3.0.8 on 2020-08-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0043_auto_20200827_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptemplate',
            name='photo_home_page',
            field=models.ImageField(null=True, upload_to='photos/Trips/%Y/%m/%d/photo_main'),
        ),
    ]
