# Generated by Django 3.0.8 on 2020-08-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0044_triptemplate_photo_home_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triptemplate',
            old_name='photo_home_page',
            new_name='photo_index',
        ),
    ]
