stages:
    - build
    - test

build website:
    stage: build
    image: froguez/travel_agency:base_django
    script:
    - apt update
    - apt upgrade -y
    - python3 -V
    - pip install -r requirements.txt
    - python3 trvgcy/manage.py runserver
    artifacts:
        paths:
            - ./public

test CI:
    stage: test
    script:
        - ls ./public


