image: froguez/travel_agency:base_django

before_script:
    - python3 -V

stages:
    - build
    - analysis
    - test
    - deploy

build website:
    stage: build
    script:
    - apt update
    - apt upgrade -y
    - apt install -y python3-venv
    - apt install -y python3-pip
    - python3 -m venv venv
    - . venv/bin/activate
    - python3 -m pip install --upgrade pip
    - pip install -r requirements.txt
    artifacts:
        paths:
            - ./public
pep8:
    stage: analysis
    script:
        - cat ./public/requirements.txt # The repository is here
        - apt update
        - apt upgrade -y
        - apt install -y python3-venv
        - apt install -y python3-pip
        - python3 -m venv venv
        - . venv/bin/activate
        - python3 -m pip install --upgrade pip
        - pip install -r requirements.txt
        - ./Test_pycodestyle.sh

# test CI:
#    stage: test
#    script:
#        - ls ./public

#deploy to DO:
#    stage: deploy
#   image: which image do you need now?
#    script:


