image: froguez/travel_agency:base_django

before_script:
    - python3 -V

stages:
    - build
    - analysis
    - test

build website:
    stage: build
    script:
    - apt update
    - apt upgrade -y
    - apt install -y python3-venv
    - apt install -y python3-pip
    - python3 -m venv venv
    - . venv/bin/activate
    - python3 -m pip install --upgrade pip
    - pip install -r requirements.txt
    artifacts:
        paths:
            - ./public
pep8:
    stage: analysis
    script:
        - apt update
        - apt upgrade -y
        - apt install -y python3-venv
        - apt install -y python3-pip
        - python3 -m venv venv
        - . venv/bin/activate
        - python3 -m pip install --upgrade pip
        - pip install -r requirements.txt
        - ./Tests/pycodestyle.sh

test CI:
    stage: test
    script:
        - ls ./public


