before_script:
    - cat generated-bash-script | su --shell /bin/bash --login user
    - echo "Hi I am here"
    - python3 -V
    - ls -l
    - echo "Before Script Finished"

stages:
    - Analysis
    - Tests

build website:
    stage: Analysis
    script: ls -l
        - echo "Stage Analysis Finished"
pep8:
    stage: Tests
    script:
        - ./Test_pycodestyle.sh
        - echo "Stage Tests Finished"