before_script:
    - echo "Hi I am here"
    - python3 -V
    - ls -l
    - echo "Before Script Finished"

stages:
    - Analysis
    - Tests
    - Release

build website:
    stage: Analysis
    script:
        - ls -l
        - echo "Stage Analysis Finished"
pep8:
    stage: Tests
    script:
        - echo "Stage Tests Finished"

git:
    stage: Release
    script:
        - pwd
        - . DO1_GitLab_runner/travel_agency.sh