stages:
    - build
    - analysis
    - test

build website:
    stage: build
    image: froguez/travel_agency:base_django
    script:
    - apt update
    - apt upgrade -y
    - python3 -V
    - python3 -m venv venv
    - . venv/bin/activate
    - python3 -m pip install --upgrade pip
    - pip install -r requirements.txt
    artifacts:
        paths:
            - ./public

pep8:
    stage: analysis
    script:
        pycodestyle trvgcy/pages/views.py


test CI:
    stage: test
    script:
        - ls ./public


