# Generated by Django 3.0.8 on 2020-08-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('active', models.BooleanField(default=None)),
            ],
        ),
    ]
