# Generated by Django 3.0.8 on 2020-08-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200807_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='firstname',
        ),
    ]
